#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RUNTIME_ROOT="${RUNTIME_ROOT:-/mnt/pfs/public/xuhaoming/instruct_gs_world}"
BASE="${RUNTIME_ROOT}/runtime/object_video_sequence_v69"
RELEASE="${BASE}/releases/${SOURCE_REVISION}"
mkdir -p "${RELEASE}/code" "${RELEASE}/docs"
cp -a "${ROOT}/code/igsw" "${RELEASE}/code/"
cp -a "${ROOT}/code/scripts" "${RELEASE}/code/"
cp "${ROOT}/docs/OBJECT_VIDEO_SEQUENCE_PLAN.md" "${RELEASE}/docs/"
cp "${ROOT}/docs/OBJECT_VIDEO_SEQUENCE_V69_RUNBOOK.md" "${RELEASE}/docs/"
cp "${ROOT}/docs/OBJECT_VIDEO_SEQUENCE_V69_REVIEW.md" "${RELEASE}/docs/"
printf '%s\n' "${SOURCE_REVISION}" > "${RELEASE}/SOURCE_REVISION"
printf '%s\n' "${SOURCE_REVISION}" > "${BASE}/DEPLOYED_REVISION"
echo "[object-video-v69-deploy] release=${RELEASE}"
