"""Arguments that must remain identical for strict checkpoint resume."""


def resume_immutable_arguments() -> tuple[str, ...]:
    return (
        "data", "dino", "data_format", "feature_source", "jit_dino_batch",
        "temporal_contract", "history_frames", "history_frames_min",
        "history_frames_max", "history_span_frames", "future_frames",
        "short_horizon_frames", "goal_query_seconds", "goal_tail_guard_frames",
        "goal_probe_frames", "goal_stability_threshold", "sequence_anchors",
        "sequence_data_sha256", "condition_cache", "condition_feature_sha256",
        "teacher_sidecar", "teacher_sidecar_sha256", "architecture",
        "training_stage", "profile", "representation_steps", "joint_steps",
        "batch", "grad_accum", "max_train_items", "lr", "lr_floor",
        "core_lr", "action_lr", "readout_lr", "dino_lr", "new_module_lr",
        "readout_scope", "current_readout_weight",
        "readout_regularization_weight", "carrier_support_weight",
        "carrier_compact_weight", "gaussian_children", "basis_gate_report",
        "carrier_preflight_report", "dense_preflight_report",
        "dense_preflight_report_sha256", "readout_gate_report",
        "readout_gate_report_sha256", "representation_gate_report",
        "representation_gate_report_sha256", "posterior_gate_report",
        "posterior_gate_report_sha256", "gate_report", "gate_report_sha256",
        "target_global_batch", "warmup_steps", "warmup_fraction",
        "weight_decay", "seed", "amp", "language_condition",
        "rgb_supervision", "rgb_short_side", "rgb_pad_multiple",
        "rgb_render_chunk", "rgb_loss_weight", "rgb_ssim_weight",
        "rgb_change_loss_weight", "rgb_change_threshold",
        "language_effect_weight", "zero_action_margin_weight",
        "zero_action_relative_margin", "aggregation_mode", "density_mode",
        "joint_flow", "posterior_dynamics_gate", "posterior_core_training",
        "posterior_update_scope", "action_anchor", "canonical_center_gate",
        "canonical_activity_gate", "canonical_activity_power",
        "action_residual_dim", "action_residual_gate", "action_residual_dropout",
        "semantic_action_basis", "goal_rollout_weight",
        "path_consistency_weight", "video_vae_model", "video_vae_contract",
        "video_vae_pythonpath",
        "video_vae_contract_sha256", "video_vae_short_side",
        "video_vae_clip_frames", "video_vae_batch",
    )
